const students = [
  {
    id: 1,
    name: "Tochukwu Mezue",
    path: "Front-end",
    information: "Fast learner",
    grade: "95.5",
    picture: "../image/tochukwu.jpeg",
  },
  {
    id: 2,
    name: "Bright Chukwudi",
    path: "Product Design",
    information: "Late to work",
    grade: "70.3",
    picture: "../image/bright.jpeg",
  },
  {
    id: 3,
    name: "Amara Metu",
    path: "Back-end",
    information: "Effective at work",
    grade: "87.65",
    picture: "../image/amara.jpeg",
  },
  {
    id: 4,
    name: "Courage Nduka",
    path: "Back-end",
    information: "Team player",
    grade: "80.7",
    picture: "../image/courage.jpeg",
  },
  {
    id: 5,
    name: "Adaeze Ugwuoke",
    path: "Product Design",
    information: "Team Leader",
    grade: "92.65",
    picture: "../image/adaeze.jpeg",
  },
  {
    id: 6,
    name: "Ifeyinwa Iyiegbu",
    path: "Front-end",
    information: "Problem Solver",
    grade: "85",
    picture: "../image/ifeyinwa.jpeg",
  },
  {
    id: 7,
    name: "Christopher Okeke",
    path: "Back-end",
    information: "Professional at work",
    grade: "89.75",
    picture: "../image/christopher.jpeg",
  },
  {
    id: 8,
    name: "Eniola Adeyeye",
    path: "Product Design",
    information: "Out-the-box Thinker",
    grade: "90.5",
    picture: "../image/eniola.jpeg",
  },
  {
    id: 9,
    name: "Samson Onyeabosi",
    path: "Front-end",
    information: "Researcher",
    grade: "88.3",
    picture: "../image/samson.jpeg",
  },
];

export default students;
